---
- name: Manage Domain Controller
  hosts: dns.mlynx.pk
  vars:
    domain_name: testmlynx.pk
    administrator_password: Qaz@zaq12)(
  tasks:
    - name: Install AD DS role
      win_feature:
        name: AD-Domain-Services
        state: present
    - name: Set domain name
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_admin_password: "{{ administrator_password }}"
        state: domain
    - name: Create Organizational Unit (OU) for computers
      win_domain:
        name: Computers
        ou: "OU=Computers,DC={{ domain_name.split('.') | join(',DC=') }}"
        state: ou
    - name: Create Organizational Unit (OU) for users
      win_domain:
        name: Users
        ou: "OU=Users,DC={{ domain_name.split('.') | join(',DC=') }}"
        state: ou
    - name: Set default password policy
      win_domain_password_policy:
        complexity: enabled
        history_count: 5
        max_password_age: 90
        min_password_age: 0
        min_password_length: 8
        password_lockout_duration: 30
        password_lockout_threshold: 5
        reversible_encryption: disabled
    - name: Configure time synchronization
      win_time:
        ntp_server: time.windows.com
        state: present
    - name: Enable firewall exceptions for domain controller
      win_firewall_rule:
        name: "{{ item }}"
        direction: in
        action: allow
        protocol: tcp
        local_port: "{{ port }}"
        remote_ip: any
        state: present
      loop:
        - "Remote Desktop"
        - "DNS Server"
        - "Kerberos Key Distribution Center"
        - "Netlogon Service"
        - "Windows Management Instrumentation (WMI)"
      vars:
        port: 53, 88, 135, 139, 389, 445, 464, 636, 3268, 3269, 49152-65535
