---
- name: Manage Domain Controller
  hosts: dns.mlynx.pk
  vars:
    domain_name: mlynx.pk
    administrator_password: Mlynx@1234
  tasks:
    - name: Install AD DS role
      win_feature:
        name: AD-Domain-Services
        state: present
    - name: Set domain name
      win_domain:
        dns_domain_name: "{{ domain_name }}"
        safe_mode_admin_password: "{{ administrator_password }}"
        state: domain
    - name: Create Organizational Unit (OU) for computers
      win_domain:
        name: Computers
        ou: "OU=Computers,DC={{ domain_name.split('.') | join(',DC=') }}"
        state: ou
    - name: Create Organizational Unit (OU) for users
      win_domain:
        name: Users
        ou: "OU=Users,DC={{ domain_name.split('.') | join(',DC=') }}"
        state: PK
