---
- name: Manage Domain Controller
  hosts: dns.mlynx.pk
  tasks:
    - name: Install AD DS role
      win_feature:
        name: AD-Domain-Services
        state: present
    - name: Set domain name
      win_domain:
        dns_domain_name: mlynx.pk
        domain_admin_user: ansible@mlynx.pk
        domain_admin_password: Mlynx@1234
        safe_mode_password: Mlynx@1234
        state: domain
    - name: Create Organizational Unit (OU) for computers
      win_domain:
        name: Computers
        ou: "OU=Computers,DC={{ mlynx.pk.split('.') | join(',DC=') }}"
        state: ou
    - name: Create Organizational Unit (OU) for users
      win_domain:
        name: Users
        ou: "OU=Users,DC={{ mlynx.pk.split('.') | join(',DC=') }}"
        state: PK
