- name: Add a user to Active Directory
  hosts: dns.mlynx.pk
  tasks:
    - name: Create the user account
      win_user:
        name: multilynx
        password: Mlynx@1234
        state: present
        groups: "Domain Users"
        password_never_expires: yes
        description: "Testing Playbook"
