---
- name: Upgrade Red Hat OS
  hosts: redhat.mlynx.pk
  become: yes
  tasks:
    - name: Check for updates
      redhat_subscription:
        state: present
        username: username
        password: pass
      register: rhn_updates

    - name: Upgrade OS
      redhat_subscription:
        state: latest
        username: username
        password: pass
      when: rhn_updates.updates_available == True
