---
- name: Gather information about last password change
  hosts: all
  become: yes
  vars:
    username: root
  tasks:
    - name: Get password change information for user
      shell: "chage -l {{ username }} | grep 'Last password change'"
      register: password_change_output
      changed_when: false

    - name: Display password change information
      debug:
        var: password_change_output.stdout_lines
