---
- name: Manage Red Hat patches
  hosts: redhat.mlynx.pk
  become: true
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Update specific package
      yum:
        name: "{{ package_name }}"
        state: latest

    - name: Remove specific package
      yum:
        name: "{{ package_name }}"
        state: absent

  vars:
    package_name: httpd
