---
- name: Create new user with encrypted password
  hosts: all
  become: yes
  vars:
    username: tayyab
    encrypted_password: "{{ 'redhat@123' | password_hash('sha512') }}"
  tasks:
    - name: Create user account
      user:
        name: "{{ username }}"
        password: "{{ encrypted_password }}"
        state: present
      become: yes
