---
- hosts: 'all'
  remote_user: root
  gather_facts: no
  vars:
    user: testing_user
    password: "{{ lookup('redhat@123', '/tmp/password chars=ascii_letters') }}"

  tasks:
    - name: Create user
      user:
        name: "{{ user }}"
        password: "{{ password | password_hash('sha512') }}"
