---
- hosts: 'all'
  remote_user: root
  gather_facts: no
  vars:
    user: testing_user
    password: "{{ 'redhat@123' }}"

  tasks:
    - name: Create user
      user:
        name: "{{ user }}"
        password: "{{ password | password_hash('sha512') }}"
